name: Prettier Check

on:
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          persist-credentials: false

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_options: "--check **/*.js"
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
